# Generated by Django 3.2.4 on 2022-06-05 09:16

import app_users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('is_client', models.BooleanField(default=False, verbose_name='user_type')),
                ('is_registered', models.BooleanField(default=False, verbose_name='is_registered')),
                ('confirmation_sent', models.BooleanField(blank=True, null=True, verbose_name='confirmation_sent')),
                ('profile_image', models.ImageField(blank=True, default='profile_img/profile_default.jpeg', upload_to='profile_img/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(default=app_users.models.CustomUser.generate_uuid, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=255)),
                ('old_email', models.EmailField(max_length=255)),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('user_uuid', models.CharField(max_length=255)),
                ('original_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replicated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
