# Generated by Django 3.2.4 on 2022-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=255)),
                ('old_email', models.EmailField(max_length=255)),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('user_uuid', models.CharField(max_length=255)),
            ],
        ),
    ]
