# Generated by Django 3.2.4 on 2022-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_img/profile_default.jpeg', upload_to='profile_img/'),
        ),
    ]
