# Generated by Django 3.2.4 on 2022-07-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disable_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
