# Generated by Django 3.2.4 on 2022-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_customuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.CharField(default='2b115a1ec5805de25d1498699a121e2dc26d2998c00d674f6bedc28d42ce7ad7', max_length=255),
        ),
    ]
