# Generated by Django 3.2.4 on 2022-05-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_userreplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreplication',
            name='original_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replicated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
