# Generated by Django 3.2.4 on 2022-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
