# Generated by Django 3.2.4 on 2022-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_customuser_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_sent',
            field=models.BooleanField(blank=True, null=True, verbose_name='confirmation_sent'),
        ),
    ]
