# Generated by Django 3.2.4 on 2022-05-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateTask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temlpatePackage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='month',
            field=models.ManyToManyField(blank=True, default=None, to='app_crm.Month'),
        ),
        migrations.AddField(
            model_name='templateaddon',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templateAddon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateaddon',
            name='template_tasks',
            field=models.ManyToManyField(blank=True, default=None, through='app_crm.addonOrderBy', to='app_crm.templateTask'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_crm.status'),
        ),
        migrations.AddField(
            model_name='task',
            name='template_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.templatetask'),
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, to='app_crm.Task'),
        ),
        migrations.AddField(
            model_name='package',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.templatepackage'),
        ),
        migrations.AddField(
            model_name='orderby',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.month'),
        ),
        migrations.AddField(
            model_name='orderby',
            name='templateTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.templatetask'),
        ),
        migrations.AddField(
            model_name='order',
            name='addon',
            field=models.ManyToManyField(blank=True, default=None, to='app_crm.Addon'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_crm.package'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_crm.status'),
        ),
        migrations.AddField(
            model_name='month',
            name='template_tasks',
            field=models.ManyToManyField(blank=True, default=None, through='app_crm.orderBy', to='app_crm.templateTask'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='app_crm.order'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_crm.message'),
        ),
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addonorderby',
            name='templateAddon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.templateaddon'),
        ),
        migrations.AddField(
            model_name='addonorderby',
            name='templateTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.templatetask'),
        ),
        migrations.AddField(
            model_name='addon',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, to='app_crm.Task'),
        ),
        migrations.AddField(
            model_name='addon',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.templateaddon'),
        ),
    ]
