# Generated by Django 3.2.4 on 2022-06-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
