# Generated by Django 3.2.4 on 2022-06-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0003_form_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='report_link',
        ),
        migrations.CreateModel(
            name='TaskReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2048)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_link', to='app_crm.task')),
            ],
        ),
    ]
