# Generated by Django 3.2.4 on 2022-05-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
