# Generated by Django 3.2.4 on 2022-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0005_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
