# Generated by Django 3.2.4 on 2022-06-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0005_notification_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-id',)},
        ),
    ]
