# Generated by Django 3.2.4 on 2022-07-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0006_templatetask_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='zapier_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
