# Generated by Django 3.2.4 on 2022-06-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0007_auto_20220603_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
