# Generated by Django 3.2.4 on 2022-07-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0007_form_zapier_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_package',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
