# Generated by Django 3.2.4 on 2022-08-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0009_remove_order_selected_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
