# Generated by Django 3.2.4 on 2022-08-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0010_form_is_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_crm.form')),
            ],
            bases=('app_crm.form',),
        ),
    ]
