# Generated by Django 3.2.4 on 2022-08-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0011_orderserviceform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderServiceForm',
        ),
    ]
