# Generated by Django 3.2.4 on 2022-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0012_delete_orderserviceform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_editable',
        ),
        migrations.AddField(
            model_name='form',
            name='is_snapshot',
            field=models.BooleanField(default=False),
        ),
    ]
