# Generated by Django 3.2.4 on 2022-08-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0013_auto_20220817_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
